config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :pillars
      resources :projects

      root to: "users#index"
    end

 devise_for :users

  authenticated :user do
	root "pillars#index", as: :authenticated_root
  end

  root "pages#home"
  get "story", to: "pages#story"

  resources :projects
  resources :pillars 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	has_one_attached :image
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Project.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Project.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :set_project, only: [:show, :update, :destory, :edit]
  before_action :authenticate_user!

  def index
  @projects = current_user.projects.all
  end

  def show

  end

  def new
  	@project = current_user.projects.build
  end

  def create
  	@project = current_user.projects.new(project_params)
    @project.image.attach(params[:project][:image])

  	respond_to do |format|
  		if @project.save
  			format.html { redirect_to projects_path}
  		else
  			format.html { render :new }
  		end
  	end
  end

  def edit
  end

  def update
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_path }
    end
  end

	private

	def set_project 
		@project = Project.find(params[:id])
	end

	def project_params
		params.require(:project).permit(:title, :summary, :why, :problem_description, :goal_statement, :project_details, :resources, :budget, :goals_extended, :success_measures, :image, :user_id)
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for (@project) do |f| %>

<%= f.error_notification %>
<%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<div class="form-inputs">
	<%= f.input :title %>
	<%= f.input :summary %>
	<%= f.input :why %>
	<%= f.input :problem_description %>
	<%= f.input :goal_statement %>
	<%= f.input :project_details %>
	<%= f.input :resources %>
	<%= f.input :budget %>
	<%= f.input :goals_extended %>
	<%= f.input :success_measures %>
	<%= f.file_field :image, class: "btn btn-outline btn-secondary" %>

</div>

<hr>

<div class="form-actions">

	<%= f.submit :submit, class: "btn btn-outline-primary" %>

</div>

<% end %>

app/views/projects/edit.html.erb
<div class="row">
	<div class="col-md-6 col-sm-12">
		<h1>Lets get this project started</h1>

		<%= render "form", project: @project %>
		

	</div>

	<div class="col">

	</div>

</div>

app/views/projects/index.html.erb
<div class="d-flex bd-highlight mb-3">
  <div class="mr-auto p-2 bd-highlight"><h3>Your Projects</h3></div>
  <div class="p-2 bd-highlight"><%= link_to "New Project", new_project_path, class: "btn btn-primary" %></div>
</div>

<div class="row" %>
  
    <% @projects.each do |project| %>
        <div class="col-md-3 col-sm-12">
            <div class="card text-center">
                <% if project.image.attached? %>
                <%= image_tag url_for(project.image), class: "card-img-top img-responsive img-project" %>
                <% else %>
                <%= image_tag url_for("surf.png"), class: "card-img-top img-responsive img-project" %>
                <% end %>
                <div class="card-body">
                    <h4 class="card-title"> <%= project.title %> </h4>
                    <%= link_to "Go to Project", project_path(project), class: "btn btn-primary btn-sm" %>
                </div>

            </div>
        </div>
    <% end %>

</div>

app/views/projects/new.html.erb
<div class="row">
	<div class="col-md-6 col-sm-12">
		<h1>Lets get this project started</h1>

		<%= render "form", project: @project %>
		

	</div>

	<div class="col">

	</div>

</div>

app/views/projects/show.html.erb
        <div class="card" style="width: 18rem;">
        <% if @project.image.attached? %>
          <%= image_tag url_for(@project.image), class: "card-img-top project-card-image" %>
        <% else %>
          <%= image_tag url_for("surf.png"), class: "card-img-topw project-card-image" %>
        <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= @project.title %></h5>
            <p class="card-text"><%= @project.summary %></p>
              <%= @project.why %>
              <%= @project.problem_description %>
              <%= @project.goal_statement %>
              <%= @project.budget %>
            <%= link_to "Edit", edit_project_path(@project), class: "btn btn-outline-primary" %>
            <%= link_to "Delete", project_path(@project), method: :delete, class: "btn btn-outline-secondary btn-sm btn-block" %>

          </div>
        </div>

 