config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :pillars
      resources :projects

      root to: "users#index"
    end

 devise_for :users

  authenticated :user do
	root "pillars#index", as: :authenticated_root
  end

  root "pages#home"
  get "story", to: "pages#story"

  resources :projects
  resources :pillars 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pillar.rb
class Pillar < ApplicationRecord
	belongs_to :user
	has_one_attached :image
end

app/controllers/admin/pillars_controller.rb
module Admin
  class PillarsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Pillar.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Pillar.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/pillars_controller.rb
class PillarsController < ApplicationController
  before_action :set_pillar, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /pillars
  # GET /pillars.json
  def index
    @pillars = current_user.pillars.all
   
  end

  # GET /pillars/1
  # GET /pillars/1.json
  def show
  end

  # GET /pillars/new
  def new
    @pillar = current_user.pillars.build
  end

  # GET /pillars/1/edit
  def edit
  end

  # POST /pillars
  # POST /pillars.json
  def create
    @pillar = current_user.pillars.new(pillar_params)
    @pillar.image.attach(params[:pillar][:image])

    respond_to do |format|
      if @pillar.save
        format.html { redirect_to pillars_path, notice: 'Pillar was successfully created.' }
        format.json { render :show, status: :created, location: @pillar }
      else
        format.html { render :new }
        format.json { render json: @pillar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pillars/1
  # PATCH/PUT /pillars/1.json
  def update
    respond_to do |format|
      if @pillar.update(pillar_params)
        format.html { redirect_to pillars_path, notice: 'Pillar was successfully updated.' }
        format.json { render :show, status: :ok, location: @pillar }
      else
        format.html { render :edit }
        format.json { render json: @pillar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pillars/1
  # DELETE /pillars/1.json
  def destroy
    @pillar.destroy
    respond_to do |format|
      format.html { redirect_to pillars_url, notice: 'Pillar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pillar
      @pillar = Pillar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pillar_params
      params.require(:pillar).permit(:title, :description, :vision, :goal_1, :goal_2, :goal_3, :project_1, :project_2, :project_3, :skill_1, :skill_2, :skill_3, :event_1, :event_2, :event_3, :time, :income, :image)
    end
end

app/helpers/pillars_helper.rb
module PillarsHelper
end

app/views/pillars/_form.html.erb
<%= simple_form_for(@pillar) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :vision %>
    <p>Pillar image</p>
    <%= f.file_field :image, class: "btn btn-secondary" %>
    <%= f.input :time %>
    <%= f.input :income %>
  </div>

<div class="accordion" id="accordionExample">
  <div class="card">
    <div class="card-header" id="headingOne">
      <h5 class="mb-0">
        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          Goals
        </button>
      </h5>
    </div>

    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">

         <div class="form-inputs">

            <%= f.input :goal_1 %>
            <%= f.input :goal_2 %>
            <%= f.input :goal_3 %>

        </div>
    </div>
  </div>


  <div class="card">
    <div class="card-header" id="headingTwo">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Projects
        </button>
      </h5>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">

          <div class="form-inputs">

            <%= f.input :project_1 %>
            <%= f.input :project_2 %>
            <%= f.input :project_3 %>

          </div>

      </div>
    </div>
  </div>

  <div class="card">
    <div class="card-header" id="headingThree">
      <h5 class="mb-0">
        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Skills
        </button>
      </h5>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
      <div class="card-body">

        <div class="form-inputs">

          <%= f.input :skill_1 %>
          <%= f.input :skill_2 %>
          <%= f.input :skill_3 %>

        </div>


      </div>
    </div>
  </div>


  <div class="card">
      <div class="card-header" id="headingThree">
        <h5 class="mb-0">
          <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            Events
          </button>
        </h5>
      </div>
      <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
        <div class="card-body">

          <div class="form-inputs">

            <%= f.input :event_1 %>
            <%= f.input :event_2 %>
            <%= f.input :event_3 %>

          </div>


        </div>
      </div>
  </div>

</div>

</div>

<hr>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pillars/_pillar.html.erb
<% @pillars.each do |pillar| %>

  <div class="col-sm-3">

      <div class="card bg-dark text-white">
        <% if pillar.image.attached? %>
          <%= image_tag url_for(pillar.image), class: "card-img pillar-img" %>

        <% else %>

          <%= image_tag ("wood.png"), class: "card-img" %>

          <% end %>
    

        <div class="card-img-overlay">
          <h5 class="card-title"><%= pillar.title %></h5>
        <p class="card-text"><%= pillar.description %></p>

        <%= link_to "Edit", edit_pillar_path(pillar), class: "card-link" %>

        </div>
      </div>

      <div class="card pillar-card">
        <div class="card-body">
          <h6 class="card-title">Vision</h6>
          <p class="card-text"><%= pillar.vision %></p>
        </div>
      </div>

      <div class="card">
        <div class="card-body">
          <h6 class="card-title">Goals</h6>
          <ol>
            <li class="card-text"><%= pillar.goal_1 %></li>
            <li class="card-text"><%= pillar.goal_2 %></li>
            <li class="card-text"><%= pillar.goal_3 %></li>
          </ol>

        </div>
      </div>

      <div class="card">
        <div class="card-body">
          <h6 class="card-title">Projects</h6>
              

          <ol>
            <li class="card-text"><%= pillar.project_1 %></li>
            <li class="card-text"><%= pillar.project_2 %></li>
            <li class="card-text"><%= pillar.project_3 %></li>
          </ol>
        </div>
      </div>

      <div class="card">
        <div class="card-body">
          <h6 class="card-title">Skills</h6>
          <ol>
            <li class="card-text"><%= pillar.skill_1%></li>
            <li class="card-text"><%= pillar.skill_2 %></li>
            <li class="card-text"><%= pillar.skill_3 %></li>
            </ol>
        </div>
      </div>

      <div class="card">
        <div class="card-body">
          <h6 class="card-title">Meetups</h6>
          <ol>
            <li class="card-text"><%= pillar.event_1%></li>
            <li class="card-text"><%= pillar.event_2 %></li>
            <li class="card-text"><%= pillar.event_3%></li>
          </ol>
        </div>
      </div>

       <div class="card">
        <div class="card-body">
          <%= link_to "Details", pillar_path(pillar), class: "btn btn-outline-primary" %>
        </div>
      </div>

 

</div>

<% end %>

app/views/pillars/_project.html.erb
<% @project.each do |project| %>

	<div class="card" style="width: 18rem;">
	<%= image_tag(url_for project.image), class: "card-img-top" %>

	  <img class="card-img-top" src="..." alt="Card image cap">
	  <div class="card-body">
	    <h5 class="card-title"><%= project.title %></h5>
	    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
	    <a href="#" class="btn btn-primary">Go somewhere</a>
	  </div>
	</div>

<% end %>

app/views/pillars/edit.html.erb
<div class="row">

	<div class="col-8">


	<%= render 'form', pillar: @pillar %>

	<br>


	</div>

	<div class="col-2 d-none d-sm-none d-md-block">


		  <div class="card bg-dark text-white">
		  	  <% if @pillar.image.attached? %>
	          	<%= image_tag url_for(@pillar.image), class: "card-img pillar-img" %>
	          <% else %>
	          	<%= image_tag ("wood.png"), class: "card-img pillar-img" %>
	          <% end %>
	        <div class="card-img-overlay">
	          <p class="card-title"><%= @pillar.title %></h5>
	        <p class="card-text"><%= @pillar.description %></p>
	        </div>
	      </div>


	</div>

</div>

app/views/pillars/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Pillar', new_pillar_path, class: "btn btn-primary" %>


<div class="row">

<%= render "pillars/pillar" %>


</div>

app/views/pillars/new.html.erb
<h1>New Pillar</h1>

<%= render 'form', pillar: @pillar %>

<%= link_to 'Back', pillars_path %>

app/views/pillars/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">

<div class="col-9">

  
<h1><%= @pillar.title %></h1>

<p><%= @pillar.description %></p>
<p> <%= @pillar.vision %> </h3>

<hr>
<h6>Goals</h4>
<ul>
    <li><%= @pillar.goal_1 %></li>
    <li><%= @pillar.goal_2 %></li>
    <li><%= @pillar.goal_3 %></li>
</ul>

<hr>

<h6>Skills</h4>

<ul>
    <li><%= @pillar.skill_1 %></li>
    <li><%= @pillar.skill_2 %></li>
    <li><%= @pillar.skill_3 %></li>
</ul>

<hr>

<h6>Events</h4>

<ul>
    <li><%= @pillar.event_1 %></li>
    <li><%= @pillar.event_2 %></li>
    <li><%= @pillar.event_3 %></li>
</ul>


</div>
  <div class="col-3">

    <div class="header-image">
            <% if @pillar.image.attached? %>
                <%= image_tag url_for(@pillar.image), class: "card-img-top img-fluid" %>
            <% else %>
                <%= image_tag url_for("surf.png"), class: "card-img-top img-fluid" %>
            <% end %>

            <br>
            
            <hr>
            

            <%= link_to 'Edit', edit_pillar_path(@pillar), class: "btn btn-primary btn-sm btn-block" %>
            <%= link_to 'Delete', pillar_path(@pillar), method: :delete, class: "btn btn-danger btn-sm btn-block" %>

    </div>

  </div>