config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :pillars
      resources :projects

      root to: "users#index"
    end

 devise_for :users

  authenticated :user do
	root "pillars#index", as: :authenticated_root
  end

  root "pages#home"
  get "story", to: "pages#story"

  resources :projects
  resources :pillars 


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
  <%= image_tag "logo.png", class: "navbar-brand img-fluid" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav d-flex">
      <%= link_to "Pillars", pillars_path, class: "nav-link" %>
      <%= link_to "Projects", projects_path, class: "nav-link" %>
      <%= link_to "My Account", edit_user_registration_path, class: "nav-link" %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
    </div>
    
  </div>
</nav>

app/views/layouts/_sideblank.html.erb
<nav class="nav flex-column">
 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Google Tag Manager -->
        <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
        new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
        j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
        'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
        })(window,document,'script','dataLayer','GTM-PVCJVVM');</script>
    <!-- End Google Tag Manager -->

    <script>
    "use strict";

    !function() {
      var t = window.driftt = window.drift = window.driftt || [];
      if (!t.init) {
        if (t.invoked) return void (window.console && console.error && console.error("Drift snippet included twice."));
        t.invoked = !0, t.methods = [ "identify", "config", "track", "reset", "debug", "show", "ping", "page", "hide", "off", "on" ], 
        t.factory = function(e) {
          return function() {
            var n = Array.prototype.slice.call(arguments);
            return n.unshift(e), t.push(n), t;
          };
        }, t.methods.forEach(function(e) {
          t[e] = t.factory(e);
        }), t.load = function(t) {
          var e = 3e5, n = Math.ceil(new Date() / e) * e, o = document.createElement("script");
          o.type = "text/javascript", o.async = !0, o.crossorigin = "anonymous", o.src = "https://js.driftt.com/include/" + n + "/" + t + ".js";
          var i = document.getElementsByTagName("script")[0];
          i.parentNode.insertBefore(o, i);
        };
      }
    }();
    drift.SNIPPET_VERSION = '0.3.1';
    drift.load('s6srd872ben5');
    </script>
    <!-- End of Async Drift Code -->

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if user_signed_in? %>

  <body class="h-100">
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PVCJVVM"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->

      <%= render "layouts/nav" %>


    <div class="container-fluid platform-body p-2 h-100">

      
      <div class="row h-100">

        <div class="col-lg-12 col-sm-12 my-auto"> 

          <%= yield %>

        </div>

      </div>

    </div> 

</body>

  <% else story_path %>

    <body class="h-100">
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PVCJVVM"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
      <div class="background_story container-fluid h-100">
              <div class="h-100">
                <div class="row landing_row h-100">

                <div class="col-lg-10 col-md-10 col-sm-12 my-auto">
                <div class="header-content mx-3">
                <%= yield %>
                  </div>
                </div>
              </div>
            </div>
          </div>
          </div> 
    
  </body>

 
    
  <% end %>
</html>